version: 3

auth:
  header_session_key: "session-id"
  session_key: "sessionid"
  logout_key: "logout"
database:
  dsn: "host=%s port=%s dbname=%s user=%s password=%s sslmode=%s"
  dbname: "test"
  host: "0.0.0.0"
  port: "5432"
  user: "test"
  password: "test"
  ssl: "disable"
redis:
  host: "0.0.0.0"
  port: "6379"
  password: ""
app:
  http_port: "8080"
  grpc_port: "8082"
grpc:
  product_api: "51.250.69.184:8082"